"""Quality scoring for the enrichment call site's actual output: a summary.

Deliberately not a fixed extraction schema (component_values / pin_count /
etc.) -- that's not what this call site produces. ``enrich.py`` asks each
model for a free-text *searchable description* of a chunk (facts, topics,
questions it could answer, visual content, alternative search terms), so
quality here means "how good is that summary", not "did every field parse".

Scored by a judge model against the original chunk content, on a 0-100
scale. Pick a judge model that isn't also being tested, so nothing is
grading its own homework.
"""

from __future__ import annotations

import re
from typing import Optional

import litellm

from .datasheet_input import TestChunk
from .harness import _litellm_model_string

_SCORE_RE = re.compile(r"SCORE\s*:\s*(\d{1,3})", re.IGNORECASE)

_THINK_BLOCK_RE = re.compile(r"<think>.*?</think>", re.IGNORECASE | re.DOTALL)
_UNCLOSED_THINK_RE = re.compile(r"<think>.*", re.IGNORECASE | re.DOTALL)

_NO_CONTENT_ERROR = (
    "model produced no content outside reasoning block "
    "(only <think>...</think> reasoning was returned)"
)


def _strip_think_blocks(text: str) -> str:
    """Remove <think>...</think> reasoning blocks before a judge sees them.

    Reasoning models (Qwen especially) prefix their real output with a
    <think> block. Left in, the judge prompt's "SUMMARY/ANSWER TO GRADE"
    section is dominated by scratch reasoning rather than the actual
    deliverable, which was producing bogus low/zero scores.

    Handles multiple blocks (all removed) and an unclosed <think> tag: if
    generation got cut off by max_tokens while still inside the reasoning
    block, there's no </think> to match, so everything from <think> to the
    end of the string is treated as reasoning too -- a model that ran out
    of budget mid-thought never produced real content after that point.
    """
    stripped = _THINK_BLOCK_RE.sub("", text)
    stripped = _UNCLOSED_THINK_RE.sub("", stripped)
    return stripped.strip()


JUDGE_PROMPT_TEMPLATE = """You are grading a searchable summary generated for a chunk of an \
electronics datasheet. Score how well the SUMMARY captures the ORIGINAL CONTENT.

Score 0-100 on these dimensions, weighted roughly evenly:
- Key facts and numbers preserved (values, ratings, part numbers)
- Coverage of the main topics/sections present in the original
- Whether the summary would actually help someone search for this content
- No fabricated details that aren't supported by the original content

ORIGINAL TEXT:
{original_text}

ORIGINAL TABLES (HTML):
{original_tables}

SUMMARY TO GRADE:
{summary}

Respond with a short rationale (2-3 sentences), then end your response on its own \
line with exactly:
SCORE: <integer 0-100>
"""


async def score_summary(
    chunk: TestChunk,
    summary: str,
    judge_model_row: dict,
) -> tuple[Optional[float], Optional[str]]:
    """Returns (score, raw_judge_response). Score is None if grading failed
    or the judge's response couldn't be parsed."""
    if not summary:
        return None, None

    cleaned_summary = _strip_think_blocks(summary)
    if not cleaned_summary:
        return None, _NO_CONTENT_ERROR

    prompt = JUDGE_PROMPT_TEMPLATE.format(
        original_text=chunk.text[:4000],
        original_tables="\n\n".join(chunk.tables)[:2000] or "(none)",
        summary=cleaned_summary[:4000],
    )

    model_string = _litellm_model_string(judge_model_row["provider"], judge_model_row["model_id"])
    kwargs: dict = dict(
        model=model_string,
        messages=[{"role": "user", "content": prompt}],
        api_key=judge_model_row["api_key"],
        temperature=0.0,
        # Judge models are often reasoning models that spend hundreds of
        # tokens on a <think> block before ever writing "SCORE: N" -- 300
        # was cutting them off mid-thought every time, well before the
        # score line. Give enough headroom for that plus the rationale.
        max_tokens=2048,
        timeout=90,
    )
    if judge_model_row.get("base_url"):
        kwargs["api_base"] = judge_model_row["base_url"]

    try:
        response = await litellm.acompletion(**kwargs)
        text = response.choices[0].message.content or ""
    except Exception as e:
        return None, f"[judge call raised {type(e).__name__}] {e}"

    match = _SCORE_RE.search(text)
    if not match:
        return None, f"[no SCORE line found in judge response] {text}"

    score = float(match.group(1))
    return max(0.0, min(100.0, score)), text


ANSWER_JUDGE_PROMPT_TEMPLATE = """You are grading an answer generated by a RAG (retrieval-augmented \
generation) system for a technical/electronics question. Score how well the ANSWER responds to the \
QUESTION using only the RETRIEVED CONTEXT it was given.

Score 0-100 on these dimensions, weighted roughly evenly:
- Correctness: does the answer match what the retrieved context actually says?
- Faithfulness: no claims that aren't supported by the retrieved context (no hallucination)
- Completeness: does it use the relevant parts of the context, not just a fragment of them?
- Relevance: does it actually address the question asked?

QUESTION:
{question}

RETRIEVED CONTEXT:
{context}

ANSWER TO GRADE:
{answer}

Respond with a short rationale (2-3 sentences), then end your response on its own \
line with exactly:
SCORE: <integer 0-100>
"""


async def score_answer(
    question: str,
    context: str,
    answer: str,
    judge_model_row: dict,
) -> tuple[Optional[float], Optional[str]]:
    """Grade a RAG answer against the question and the context it was given.

    Returns (score, raw_judge_response). Score is None if grading failed or
    the judge's response couldn't be parsed. Separate from ``score_summary``
    because the rubric is genuinely different -- this grades an answer's
    correctness/faithfulness to given context, not a summary's coverage of
    original content.
    """
    if not answer:
        return None, None

    cleaned_answer = _strip_think_blocks(answer)
    if not cleaned_answer:
        return None, _NO_CONTENT_ERROR

    prompt = ANSWER_JUDGE_PROMPT_TEMPLATE.format(
        question=question[:2000],
        context=context[:6000],
        answer=cleaned_answer[:4000],
    )

    model_string = _litellm_model_string(judge_model_row["provider"], judge_model_row["model_id"])
    kwargs: dict = dict(
        model=model_string,
        messages=[{"role": "user", "content": prompt}],
        api_key=judge_model_row["api_key"],
        temperature=0.0,
        max_tokens=2048,
        timeout=90,
    )
    if judge_model_row.get("base_url"):
        kwargs["api_base"] = judge_model_row["base_url"]

    try:
        response = await litellm.acompletion(**kwargs)
        text = response.choices[0].message.content or ""
    except Exception as e:
        return None, f"[judge call raised {type(e).__name__}] {e}"

    match = _SCORE_RE.search(text)
    if not match:
        return None, f"[no SCORE line found in judge response] {text}"

    score = float(match.group(1))
    return max(0.0, min(100.0, score)), text
